### ISSUE TITLE
Login Screen Loop 

### ISSUE THREAD

**Issue by MartinEnders** [nextcloud/docker#1270]
Hi,

when I was setting the redis connection parameters in docker-compose file it resulted in a login-loop.
When I logged in I have been redirected to the login-page immediatly.
Setup: everything in docker, nginx reverse proxy in front of apache-20 version of nextcloud

When I removed the redis-config from the environment it worked fine (s. link below).
I assume that redis is working because it is inserted in the config.php file.

https://help.nextcloud.com/t/login-loop-after-updating-dockerized-nextcloud-to-version-19/88705/3

Now my nextcloud setup works fine.

Best regards
Martin

**Comment by J0WI** [comment]
fixed in #1232

**Comment by briancsimonsen** [comment]
This issue is not fixed. After pulling the latest stable version I was still able to recreate the issue.
The issue #1232 is not the same problem because that issue was caused by leaving the password blank. This problem here is caused by having the password filled in and by doing so, causing a loop.

**Comment by Shurov** [comment]
I faced the same problem, however I have a workaround and a hint to possible problem.
- So, after clean install via docker and creating admin user - login screen was looping. This was done in a web-browser on a PC, pointing to the local installation (http://192.168.0.100:8080)
- I configured a reverse proxy (nginx) with LetsEncrypt certificate for it, being accessible at https://nextcloud.example.com. And it works! (this is a workaround part)
- I tried to configure official Android app to contact my server via a domain name.... And the app also has a login loop, however, it also shows an error `Strict mode: no http connection allowed`. (this is a hint part). But I'm not sure how to fix it. I'd like to move all the installation onto the HTTPS - even local access, but I can't find any manual how to do it using (official) docker install

**Comment by Rebanar** [comment]
I found this issue since Shurov's comment has the issue I was searching for regarding the android app. I have a similar setup using caddy to make everything go through https.

I was able to solve the issue by adding 'overwriteprotocol' => 'https' to my config.php file. This forces it to use https since it doesn't actually know it's being set to https via the reverse proxy.

I don't know if this has anything to do with the original issue, but since I found my way here through a web search I figured someone else might too.

**Comment by cyberjacob** [comment]
That workaround isn't ideal, as it would allow any connections not being made through https for whatever reason. If you're using that I would suggest having your reverse proxy only accept HTTPS and redirect everything attempting to use HTTP.

For a perminant solution, Nextcloud would need to add support for the [`X-Forwarded-Proto`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) header

**Comment by hynet-mel** [comment]
Still have this issue here too.

**Comment by dR3b** [comment]
Same shit here! Rebanar solution fixed it!

adding 'overwriteprotocol' => 'https' to config.php

**Comment by Chlorgas** [comment]
Hey!

I'm on unraid 6.9.2 with Nextcloud Hub II (23.0.3) as Docker (20.10.5) behind a pfSense 2.6.0 with haproxy (0.61_5) and had the same Problem. Logins from the same subnet went good, but external login ended in looping the login after input of username and password.
Different changes in nextcloud's config.php (trustetd:domains, overwrite.cli.url, overwriteprotocol, trusted_proxies, forwarded_for_headers an so on) does not solve the problem.

my solution: in haproxy simply redirect FQDN port 80 and port 443 at the frontend to one backend at port 443 with valid certificates.

**Comment by joshtrichards** [comment]
The original report here was indeed #1232. The rest of these matters are different. If still experiencing them in an existing installation I suggest:

- update your container's `config/` files (see #1533 since they may be out-of-date and we don't automatically update them for safety purposes)
- post your Compose file on the help forum (https://help.nextcloud.com) so that someone else can analyze it and try to reproduce the problem or suggest where the cause may be
- If you still believe there is a bug today, create a *dedicated* issue containing:
  - your full Compose file
  - the output of `occ config:list system` (<-- important since the image uses multiple config files, not just your main `config.php`).
