### ISSUE TITLE
Image 27.0.1-fpm reports Nextcloud data version is lower and won't start

### ISSUE THREAD

**Issue by ArjenR** [nextcloud/docker#2042]
When starting the new container the following message appears:

nextcloud      | Can't start Nextcloud because the version of the data ( 
nextcloud      | 27.0.0.8) is higher than the docker image version (                                                                                                                                                                                    
nextcloud      | 27.0.1.2) and downgrading is not supported. Are you sure you have pulled the newest image version?

Pulling fpm-27.0.0 reverted the issue and the container boots.

**Comment by dli7319** [comment]
I think this was caused by the warning described in #2037 which was fixed in #2033 .

To avoid this in the future, it may be useful to have something like `--define display_errors=stderr` when detecting the versions though in https://github.com/nextcloud/docker/blob/7bd3b7b6dbd694bab3612a28b17a9767f2339c9e/docker-entrypoint.sh#L147 and https://github.com/nextcloud/docker/blob/7bd3b7b6dbd694bab3612a28b17a9767f2339c9e/docker-entrypoint.sh#L150.

**Comment by Sim0nW0lf** [comment]
https://github.com/nextcloud/docker/issues/2037#issuecomment-1662009249

This is the solution

**Comment by ArjenR** [comment]
> 

Yes, still the same errors.  Made sure I pulled the latest which was built 2 hours ago. 

```
nextcloud      | 27.0.0.8) is higher than the docker image version (
nextcloud      | Warning: PHP Startup: Unable to load dynamic library 'imap.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so (libc-client.so.2007e: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
nextcloud      | 27.0.2.1) and downgrading is not supported. Are you sure you have pulled the newest image version?
nextcloud exited with code 1

```

**Comment by ArjenR** [comment]
I deemed this issue to be upstream.

After reviewing the layers in the fpm-27 I noticed the patch is applied (currently for sure). Further investigation revealed the same patch is necessary downstream too. 

Closing as resolved.
