### ISSUE TITLE
Document how to run with specified user

### ISSUE THREAD

**Issue by bmaehr** [nextcloud/docker#2354]
According to https://github.com/nextcloud/docker/pull/1812 it is possible to run the docker images with a specivied user. I was not able to make it working.

I use docker compose tu run the images and added 

```
services:
  nextcloud-fpm:
    image: nextcloud:fpm-alpine
    user: 33:33

```
where 33 is the id of www-data on the host system.

But I still get the mesage that `config.php` is read-only.

If i do a `docker exec -it cloud-nextcloud-fpm-1 sh` Im abel to write `config.php`, but not if I do `docker compose exec --user www-data nextcloud-fpm sh`. This gives me

``` 
/var/www/html $ whoami
whoami: unknown uid 82
```

I'm confused.

Is it caused by
```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

```

**Comment by tzerber** [comment]
It's caused by [this line and the ones below it](https://github.com/nextcloud/docker/blob/616d0dff033b4354e5ff3e411e530980733f1d03/30/fpm/entrypoint.sh#L98). This is a bug and should be fixed.

**Comment by bmaehr** [comment]
I just recreated the container by deleting the container and volume. Still the same issue, 

The container was created by a simple "docker compose up"

The compose file:
``` 
services:
  fpm:
    image: nextcloud:fpm-alpine
    container_name: cloud-fpm
    restart: always
    user: 33:33
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - nextcloud:/var/www/html:z
      - /srv/cloud/config.php:/var/www/html/config/config.php
      - /var/log/cloud:/var/log/cloud
      - /srv/cloud/data:/var/www/html/data
      - /srv/cloud/apps:/var/www/html/custom_apps
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloud
      - MYSQL_PASSWORD=9....38
      - MAIL_DOMAIN=mydomain.com
      - MAIL_FROM_ADDRESS=cloud
      - SMTP_HOST=mail.mydomain.com
      - SMTP_PORT=25
      - SMTP_SECURE=tls
      - NEXTCLOUD_ADMIN_USER=myuser
      - NEXTCLOUD_ADMIN_PASSWORD=mypassword
    networks:
      - docker_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      tags:
        - "cloud-nginx-proxy:latest"
    container_name: cloud-nginx
    restart: always
    volumes:
      - nextcloud:/var/www/html:z,ro
      - /srv/cloud/data:/var/www/html/data
      - /srv/cloud/apps:/var/www/html/custom_apps
      # NOTE: The `volumes` included here should match those of the `app` container (unless you know what you're doing)
    networks:
      - docker_network
    ports:
      - 127.0.0.1:11000:80
    depends_on:
      - fpm

  redis:
    image: redis:alpine
    container_name: cloud-redis
    restart: always

  cron:
    image: nextcloud:fpm-alpine
    container_name: cloud-cron
    restart: always
    user: 33:33
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - nextcloud:/var/www/html:z
      - /var/log/cloud:/var/log/cloud
      - /srv/cloud/config.php:/var/www/html/config/config.php:ro
      - /srv/cloud/data:/var/www/html/data
      - /srv/cloud/apps:/var/www/html/custom_apps
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: /cron.sh
    depends_on:
      - redis

volumes:
  nextcloud:

networks:
  docker_network:
    ipam: 
      driver: default
      config:
        - subnet: 172.22.1.0/24

```

**Comment by bmaehr** [comment]
```
/var/www/html/config $ ls -l -a
total 16
drwxr-xr-x    2 root     root          4096 Jan 25 09:33 .
drwxrwxrwt   16 82       root          4096 Jan 25 09:33 ..
-rw-------    1 www-data www-data      6363 Dec 19 16:38 config.php
```

**Comment by tzerber** [comment]
The alpine based image has the www-data user as uid 82, the normal fpm image has www-data as user 33. If you use the UID 33 then run the non-alpine image, i.e. 
```yaml 
image: nextcloud:fpm
```

**Comment by bmaehr** [comment]
But my host system has www-data at 33 and i would like the cloud in the docker to have access to the files on the host system.

**Comment by tzerber** [comment]
You are probably trying to do something the wrong way (I'm guessing here). Please describe the full problem on what exactly you're trying to do.

**Comment by bmaehr** [comment]
Abstract description: I have files on the host systems with certain permissions (e.g. in this case 33) and would like to run an application in a docker container ( e.g. in this case fpm-alpine) with a user that has the permission to access these files.

**Comment by tzerber** [comment]
Linux file&folder permissions exists for a reason , and I am assuming you're using debian-based host OS. If not - please adapt with the commands or tell me host OS.

Easy solution: Ditch the alpine image and use the debian based FPM image, so the UID match. Keep in mind that app & cron dockers need to use the same image. Check my last comment for info.

Hard solution if alpine image is a must (and since host's trying to access NC's files) : First check if uid 82 is free on your host, using `sudo getent passwd` and `sudo getent group`, look for the UIDs.
If id and group 82 are free, create a group with a human-understandable name like `sudo groupadd -g 82 nextcloud-files` then add the www-data user to that group using `sudo usermod -aG nextcloud-files www-data` .
If GUID exist post back what's using it and is it acceptable to have www-data user in that group.

**Comment by tzerber** [comment]
In your case, with mounting all these folders/files (don't mount passwd file, its very bad idea) just use the normal non-alpine image.

**Comment by bmaehr** [comment]
``` 
Linux file&folder permissions exists for a reason
```
Of course. 

I just couldn't image that running a docker image with a specific user almost 40 years after inventing `su` could be a problem.

I will try you suggested workaround.

**Comment by tzerber** [comment]
> ```
> Linux file&folder permissions exists for a reason
> ```
> 
> Of course.
> 
> I just couldn't image that running a docker image with a specific user almost 40 years after inventing `su` could be a problem.
> 
> I will try you suggested workaround.

It's not that easy to "just use su" when it comes to docker containers. 
And it appears to me that you're trying to use the files from NC on the host via the NC on docker(No idea why, again). I'm fairly sure this is the most workaround-ed solution there is when it comes to running nextcloud in docker. I would suggest do a fresh install via docker, and just move all the files then chmod them to match the data in the container, from within the container itself. Then again, this is also a "not so documented" way of doing what you're doing. The only reasonable advice I can give you is to use the debian based image of NC-fpm, all other solutions will cause more problems in the long run.

**Comment by bmaehr** [comment]
You are right, that is what I'm doing.
Because for me docker is an abstraction layer for the application from the os. And I'm really surprised that there is no practical solution of abstracting the user ids.

And of course I want to have the data on the host and not inside the container or a volume.

In my case I easily could change the permission easyly by chown but it is an awful workaround and that would be necessary if i switch between alpine and not shows how wrong it is.

**Comment by tzerber** [comment]
> You are right, that is what I'm doing. Because for me docker is an abstraction layer for the application from the os. And I'm really surprised that there is no practical solution of abstracting the user ids.

The problem with that is that docker is effectively isolating the environment rather than just sharing it. From container's point of view it's a bare OS with it's files.

> 
> And of course I want to have the data on the host and not inside the container or a volume.
>
I strongly suggest you read [this document](https://docs.docker.com/engine/storage/bind-mounts/ ). Anyway, files are always stored on the host, even without bind mount, they are just on different location (usually /var/lib/docker/volumes). Bind mount is just mounting between host and container.

> In my case I easily could change the permission easyly by chown but it is an awful workaround and that would be necessary if i switch between alpine and not shows how wrong it is.

Alpine is not debian-based, that's why it has it's "usual" UID-s different and requiring chown.  Your plan would worked, if you didn't use the alpine image (and didn't mount passwd and groups, breaking god knows how many other things inside the alpine generated container).

Also, you should remove this from your compose, in the nginx section, it's pointless if you're bind mounting stuff on top of it : 
```yaml
 - nextcloud:/var/www/html:z,ro
```

**Comment by joshtrichards** [comment]
`--user` / `user` is not a construct of this image. It's a parameter in Docker. This really isn't the appropriate channel to be doing general troubleshooting or learning about container environments. I'm not discouraging learning, but I suggest utilizing a more appropriate channel -- e.g. Stack Overflow, the Docker forum, the Docker documentation, or the Nextcloud help forum.

This channel must be kept clear for managing bugs with the image specifically.

That said, you'll save yourself a lot of trouble if you use `--user 33:33` versus `-u www-data:www-data`, which will fix your original problem. 

The original issue you ran into is that `--user` uses the image's `/etc/passwd` (not your mounts). You can confirm this by trying to exec as a user that is *only* in the pre-overwritten `/etc/passwd` file, such as the `guest` user in the fpm-alpine image. e.g.

 `docker exec --user guest -it whoami`

`guest` will still be resolved for the `exec` to `405:100` even though it's (likely) not in your replacement `/etc/passwd`.

You would have the same problem at runtime, but within your Compose file you're doing it correctly already (`user: 33:33`).

**Comment by joshtrichards** [comment]
Since this is not a bug in the image, I'm going to close this Issue out.

P.S. The inability to write a config is likely because your `config/` folder itself is shown as owned by root. (I believe the error you speak of actually references the folder not the file, but you didn't include the exact error you're seeing so I can only guess). 

The ownership will all be `33:33` automatically if you deploy with `33:33` specified at the start. At least it will be if you provide a mount for a `config/` **folder** outright (as specified in our docs).

Mounting *only* a `config/config.php` **file** (at install time; which also doesn't really make sense since the installer needs to create this file not you) will prevent installation of the image's own config files (which need to coexist in the same folder) and lead to parent folder ownership problems. There are almost certainly other signs of this in your environment, such as environment variables being ignored + startup errors and warnings in your app container logs.

Lastly, I would not mount a replacement `/etc/passwd` from an entirely different OS. Just using `33:33` should be sufficient. All processes/etc will use that UID/gid combo as well as all file ownership. Mapping `www-data` to `33` *in* the container is not required when using `--user`.  I think maybe you're overthinking that part. :-)
